class Dmart{
	
	public static void main(String chats[]){
	String groceries[] = {"Bread","Cereal","Crackers","Chips","Nuts","popcorn","pasta","juice","pancakes","cake mixes","miffin mixes","suger","water","soft drinks","tea","coffee","soda","viniger","ketchap","fish"};
	String vegatables[] = {"Pumpkin","pea","Corn","radish","Beet","Eggplant","Clementines","","lemons","limes","Avacado","peppers","carrots","Cauliflower","Tomatoes","cucumber","spinach","Potato","cabbage","ginger"};
	String clothBrands[] = {"Levis","H&M","Adidas","BIBA","AllenSolly","Fabindia","Louis Phillippe","Mufti","Armani","Chanel","Flying Machine","Harmes","Calvin Klein","Max Fashion","pepe jeans","prada","Puma","Reebok","woodland","Being Human"};
	String toyNames[] = {"bicycle","trains","doll","ball","teddy bear","kite","rubber ducky","airplane","crayons","rocking horse","cars","drums","DollHouse","playTent","Magic set","Toy camera","yo-yo","marbles","Hand Puppets","plush toys"};
	String fruits[] = {"bananas","grapes","Peaches","Plums","Apples","Strawberries","pineapple","Mango","Guava","waterMelon","papaya","kiwi","blueberry","pomegranate","apricot","orange","cherry","fig","luchee","raspberry"};
	String homeAppliances[] = {"Microwave","Air Conditioner","washing machine","Blender","Coffee Machine","dish washer","dryer","heater","stove","toaster","iron","juicer","air fryer","tv","Kettles","Fan","vacuum cleaner","lamp","torach","light bulb"};
	String perfumes[] = {"Anna sui","Armaf","Aveda","aramis","armani","barber Pro","Balmain","Beyonce","Cacharel","Calvin klein","Chanel","clean","coach","david beckhan","Cecleeor","Dior","Dove","Valentiono","Versace","victorias Scret"};
	String soaps[] = {"Himalaya","Dettol","bio orange peel","pears","sebamed","cataphil","dove","lux","nivea","beauty soap","medimix","khadi sandalwoon","mysore sandal","santoor","cinthol","biotique","Fima Di Wills","margo","srisri","Lifebuoy"};
	String alcohols[] = {"Beer","Wine","Champagne","Hard cider","mead","sake","gin","brandy","whiskey","rum","tequila","vodka","soju","everclear","Absinthe","Baileys Irish cream","Smirnoff","Jack Daniels","DOM perignon","captain morgan"};
	String biscuits[] = {"Parle-G","monaco","krackjack","2020 cookies","hide and  seek","milano","nitri crunch","Magix","milk sakthi","good day","jim jim","bourbon","marie gold","tiger","pure magic","little hearts","milk bilis","crackers","jadoo","sunfeast"};
	String dairyProducts[] = {"Irish Butter","kaymak","cotted cream","butter","greek yogurt","mlyako","yogurt","ghee","cream","malai","kashk","matzoon","milk","condenced milk","paneer","milk powder","curd","whey","kefir","butter milk"};

	System.out.println(" groceries Names are " + groceries[0] + "|" + groceries[1] + "|" + groceries[2]+ "|" + groceries[3]+ "|" + groceries[4]+ "|" + groceries[5]+ "|" + groceries[6]+ "|" + groceries[7]+ "|" + groceries[8]+ "|" + groceries[9]+ "|" + groceries[10]+ "|" + groceries[11]+ "|" + groceries[12]+ "|" + groceries[13]+ "|" + groceries[14]+ "|" + groceries[15]+ "|" + groceries[16]+ "|" + groceries[17]+ "|" + groceries[18]+ "|" + groceries[19]);
	System.out.println(" vegatables Names are " + vegatables[0] + "|" + vegatables[1] + "|" + vegatables[2]+ "|" + vegatables[3]+ "|" + vegatables[4]+ "|" + vegatables[5]+ "|" + vegatables[6]+ "|" + vegatables[7]+ "|" + vegatables[8]+ "|" + vegatables[9]+ "|" + vegatables[10]+ "|" + vegatables[11]+ "|" + vegatables[12]+ "|" + vegatables[13]+ "|" + vegatables[14]+ "|" + vegatables[15]+ "|" + vegatables[16]+ "|" + vegatables[17]+ "|" + vegatables[18]+ "|" + vegatables[19]);
	System.out.println(" Cloths Brands Names are " + clothBrands[0] + "|" + clothBrands[1] + "|" + clothBrands[2]+ "|" + clothBrands[3]+ "|" + clothBrands[4]+ "|" + clothBrands[5]+ "|" + clothBrands[6]+ "|" + clothBrands[7]+ "|" + clothBrands[8]+ "|" + clothBrands[9]+ "|" + clothBrands[10]+ "|" + clothBrands[11]+ "|" + clothBrands[12]+ "|" + clothBrands[13]+ "|" + clothBrands[14]+ "|" + clothBrands[15]+ "|" + clothBrands[16]+ "|" + clothBrands[17]+ "|" + clothBrands[18]+ "|" + clothBrands[19]);
	System.out.println(" Toys Names are " + toyNames[0] + "|" + toyNames[1] + "|" + toyNames[2]+ "|" + toyNames[3]+ "|" + toyNames[4]+ "|" + toyNames[5]+ "|" + toyNames[6]+ "|" + toyNames[7]+ "|" + toyNames[8]+ "|" + toyNames[9]+ "|" + toyNames[10]+ "|" + toyNames[11]+ "|" + toyNames[12]+ "|" + toyNames[13]+ "|" + toyNames[14]+ "|" + toyNames[15]+ "|" + toyNames[16]+ "|" + toyNames[17]+ "|" + toyNames[18]+ "|" + toyNames[19]);
	System.out.println(" Fruits Names are " + fruits[0] + "|" + fruits[1] + "|" + fruits[2]+ "|" + fruits[3]+ "|" + fruits[4]+ "|" + fruits[5]+ "|" + fruits[6]+ "|" + fruits[7]+ "|" + fruits[8]+ "|" + fruits[9]+ "|" + fruits[10]+ "|" + fruits[11]+ "|" + fruits[12]+ "|" + fruits[13]+ "|" + fruits[14]+ "|" + fruits[15]+ "|" + fruits[16]+ "|" + fruits[17]+ "|" + fruits[18]+ "|" + fruits[19]);
	System.out.println(" homeAppliances Names are " + homeAppliances[0] + "|" + homeAppliances[1] + "|" + homeAppliances[2]+ "|" + homeAppliances[3]+ "|" + homeAppliances[4]+ "|" + homeAppliances[5]+ "|" + homeAppliances[6]+ "|" + homeAppliances[7]+ "|" + homeAppliances[8]+ "|" + homeAppliances[9]+ "|" + homeAppliances[10]+ "|" + homeAppliances[11]+ "|" + homeAppliances[12]+ "|" + homeAppliances[13]+ "|" + homeAppliances[14]+ "|" + homeAppliances[15]+ "|" + homeAppliances[16]+ "|" + homeAppliances[17]+ "|" + homeAppliances[18]+ "|" + homeAppliances[19]);
	System.out.println(" perfumes Names are " + perfumes[0] + "|" + perfumes[1] + "|" + perfumes[2]+ "|" + perfumes[3]+ "|" + perfumes[4]+ "|" + perfumes[5]+ "|" + perfumes[6]+ "|" + perfumes[7]+ "|" + perfumes[8]+ "|" + perfumes[9]+ "|" + perfumes[10]+ "|" + perfumes[11]+ "|" + perfumes[12]+ "|" + perfumes[13]+ "|" + perfumes[14]+ "|" + perfumes[15]+ "|" + perfumes[16]+ "|" + perfumes[17]+ "|" + perfumes[18]+ "|" + perfumes[19]);
	System.out.println(" soaps Names are " + soaps[0] + "|" + soaps[1] + "|" + soaps[2]+ "|" + soaps[3]+ "|" + soaps[4]+ "|" + soaps[5]+ "|" + soaps[6]+ "|" + soaps[7]+ "|" + soaps[8]+ "|" + soaps[9]+ "|" + soaps[10]+ "|" + soaps[11]+ "|" + soaps[12]+ "|" + soaps[13]+ "|" + soaps[14]+ "|" + soaps[15]+ "|" + soaps[16]+ "|" + soaps[17]+ "|" + soaps[18]+ "|" + soaps[19]);
	System.out.println(" alcohols Names are " + alcohols[0] + "|" + alcohols[1] + "|" + alcohols[2]+ "|" + alcohols[3]+ "|" + alcohols[4]+ "|" + alcohols[5]+ "|" + alcohols[6]+ "|" + alcohols[7]+ "|" + alcohols[8]+ "|" + alcohols[9]+ "|" + alcohols[10]+ "|" + alcohols[11]+ "|" + alcohols[12]+ "|" + alcohols[13]+ "|" + alcohols[14]+ "|" + alcohols[15]+ "|" + alcohols[16]+ "|" + alcohols[17]+ "|" + alcohols[18]+ "|" + alcohols[19]);
	System.out.println(" biscuits Names are " + biscuits[0] + "|" + biscuits[1] + "|" + biscuits[2]+ "|" + biscuits[3]+ "|" + biscuits[4]+ "|" + biscuits[5]+ "|" + biscuits[6]+ "|" + biscuits[7]+ "|" + biscuits[8]+ "|" + biscuits[9]+ "|" + biscuits[10]+ "|" + biscuits[11]+ "|" + biscuits[12]+ "|" + biscuits[13]+ "|" + biscuits[14]+ "|" + biscuits[15]+ "|" + biscuits[16]+ "|" + biscuits[17]+ "|" + biscuits[18]+ "|" + biscuits[19]);
	System.out.println(" dairyProducts Names are " + dairyProducts[0] + "|" + dairyProducts[1] + "|" + dairyProducts[2]+ "|" + dairyProducts[3]+ "|" + dairyProducts[4]+ "|" + dairyProducts[5]+ "|" + dairyProducts[6]+ "|" + dairyProducts[7]+ "|" + dairyProducts[8]+ "|" + dairyProducts[9]+ "|" + dairyProducts[10]+ "|" + dairyProducts[11]+ "|" + dairyProducts[12]+ "|" + dairyProducts[13]+ "|" + dairyProducts[14]+ "|" + dairyProducts[15]+ "|" + dairyProducts[16]+ "|" + dairyProducts[17]+ "|" + dairyProducts[18]+ "|" + dairyProducts[19]);
	}
}